### PR TITLE
Test merge upstream

### PR DESCRIPTION
**Pull request by marco-m-pix4d**
This PR is just to show the contents of the merge from upstream

```
git merge --no-ff -m 'Merge branch 'concourse:master' into master' 402694a5c
```

Where the SHA is the merge of this PR https://github.com/concourse/concourse/pull/8928

I mentioned that I wanted to cherry-pick, but since it turns out that that merge is the first merge on upstream master after our last sync, I am just merging.

Then I will try to push the merge directly from master, this PR will not be merged.

The corresponding CI is passing, see pipeline concourse-fork-test-merge-upstream, job `concourse-linux`, task `yarn-build`. NOTE the CI check below seems red only because I aborted the build once it passed the task `yarn-build`.

### CODE REVIEW

**Comment by marco-m-pix4d** [comment]
Ah. The CodeQL comes from an upstream GitHub action. Do we want to keep it?

**Comment by marco-m-pix4d** [comment]
If I try to push master, I get
```
git push origin master
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Waiting on code owner review from Pix4D/integration.
To github.com:Pix4D/concourse.git
 ! [remote rejected]       master -> master (protected branch hook declined)
error: failed to push some refs to 'github.com:Pix4D/concourse.git'
```

This makes me think that GitHub sees that the commit is the same on master and on this branch (the one of this PR)...

**Comment by odormond** [comment]
Also the PR is not approved so you should not be allowed to merge.

**Review by odormond — APPROVED** [review]

**Review by iAmoric — APPROVED** [review]

**Comment by marco-m-pix4d** [comment]
So I pushed master and that caused this PR to me marked as merged 😁

**Comment by odormond** [comment]
> So I pushed master and that caused this PR to be marked as merged 😁

Yep. Merge, tag and push is our newly documented release strategy. :smile:

**Comment by marco-m-pix4d** [comment]
> > So I pushed master and that caused this PR to be marked as merged 😁
> 
> Yep. Merge, tag and push is our newly documented release strategy. 😄

Yes. What I meant is that this PR is not from the master branch, which would be impossible, is from branch test-merge-upstream. What I did was pushing the master branch, which had an effect on this PR. 

My interpretation is that:

> This makes me think that GitHub sees that the commit is the same on master and on this branch (the one of this PR)...

**Pull request merged**
